choco install firefox -y
choco install nodejs-lts -y
choco install discord -y
choco install vscode -y
choco install steam -y
choco install androidstudio -y
choco install visualstudio2022community -y
choco install 7zip -y
choco install oraclejdk -y
choco install powertoys -y
choco install sharex -y
choco install winscp -y
choco install wireguard -y
